### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by pwntester** [hrsh7th/deoplete-vim-lsc#1]
Hi,

Can you please add documentation on how to configure and use the plugin?

Thanks!

**Comment by pwntester** [comment]
Seems all its needed is to disable vim-lsc autocompletion and add this plugin

**Comment by motorto** [comment]
Thanks ! @pwntester ,
I was in the same boat as you , and reading your comment was the solution.

Nevertheless documentation is a must ! So closing this issue is not the solution 

EDIT: still don't know how to work with this :), Do I have to configure something else besides disable vim-lsc autocompete ?
